<?php

$imageMetadata = require __DIR__.'/kotajail-images.php';

return [
    'site' => [
        'name' => 'Kota Jail',
        'tagline' => 'Johor Bahru Heritage Experience',
        'description' => 'A self-guided digital tour for Kota Jail, the former Ayer Molek Prison in Johor Bahru, Malaysia.',
        'keywords' => 'Kota Jail Johor, Kota Jail Johor Bahru, Kota Jail self-guided tour, Ayer Molek Prison, Johor Bahru heritage attraction, Johor Bahru historical site, Heritage tourism Johor, Art and culture Johor Bahru',
        'address' => 'Penjara (lama) Ayer Molek, Jalan Ayer Molek, 80888 Johor Bahru, Malaysia',
        'email' => 'hello@kotajail.com',
        'phone' => '+6016-721 5646',
        'hours' => 'Open daily, 10:00 AM - 10:00 PM',
        'established' => '1883',
        'image' => $imageMetadata['sections']['hero']['image'],
        'alt' => $imageMetadata['sections']['hero']['alt'],
        'image_credit' => $imageMetadata['sections']['hero']['credit'],
        'image_source_name' => $imageMetadata['sections']['hero']['source_name'],
        'image_source_url' => $imageMetadata['sections']['hero']['source_url'],
        'image_photographer' => $imageMetadata['sections']['hero']['photographer'],
        'image_position' => $imageMetadata['sections']['hero']['position'],
        'image_width' => $imageMetadata['sections']['hero']['width'],
        'image_height' => $imageMetadata['sections']['hero']['height'],
        'social' => [
            'Instagram' => 'https://www.instagram.com/',
            'X' => 'https://x.com/',
            'WhatsApp' => 'https://wa.me/60167215646',
        ],
    ],

    'stats' => [
        ['label' => 'Established', 'value' => '1883'],
        ['label' => 'Tour stops', 'value' => '10'],
        ['label' => 'Suggested pace', 'value' => '60 min'],
        ['label' => 'Open daily', 'value' => '10am-10pm'],
    ],

    'features' => [
        [
            'icon' => 'map',
            'title' => 'Interactive Map',
            'description' => 'Follow an easy route between editable stops with a map view and a list view for accessible browsing.',
        ],
        [
            'icon' => 'headphones',
            'title' => 'Audio Guide',
            'description' => 'Use a designed sample audio interface with transcripts and graceful messaging when audio files are not yet added.',
        ],
        [
            'icon' => 'qr-code',
            'title' => 'QR Checkpoints',
            'description' => 'A visitor-ready QR explanation flow supports future on-site codes without needing a backend today.',
        ],
        [
            'icon' => 'check-circle',
            'title' => 'Tour Progress',
            'description' => 'Mark places as completed and resume from the next recommended stop using browser local storage.',
        ],
        [
            'icon' => 'languages',
            'title' => 'Bilingual Content',
            'description' => 'Language preferences are saved locally and the structure is ready for English and Bahasa Malaysia copy.',
        ],
        [
            'icon' => 'accessibility',
            'title' => 'Accessible Experience',
            'description' => 'Large touch targets, keyboard states, transcripts, list alternatives, and reduced-motion support are built in.',
        ],
    ],

    'tour_routes' => [
        [
            'slug' => 'highlights',
            'name' => '30-Minute Highlights Tour',
            'duration' => '30 minutes',
            'stops' => 4,
            'distance' => 'Walking distance to be verified',
            'difficulty' => 'Easy',
            'description' => 'A concise route for first-time visitors who want a respectful overview of the site.',
        ],
        [
            'slug' => 'heritage',
            'name' => '60-Minute Heritage Tour',
            'duration' => '60 minutes',
            'stops' => 7,
            'distance' => 'Walking distance to be verified',
            'difficulty' => 'Moderate',
            'description' => 'A balanced self-guided route through history, architecture, and present-day cultural use.',
        ],
        [
            'slug' => 'complete',
            'name' => 'Complete Kota Jail Experience',
            'duration' => '90 minutes',
            'stops' => 10,
            'distance' => 'Walking distance to be verified',
            'difficulty' => 'Moderate',
            'description' => 'The fullest visitor route, designed for slower reading, photographs, and reflection.',
        ],
        [
            'slug' => 'art-culture',
            'name' => 'Art and Culture Route',
            'duration' => '45 minutes',
            'stops' => 5,
            'distance' => 'Walking distance to be verified',
            'difficulty' => 'Easy',
            'description' => 'A creative route focused on galleries, exhibitions, community activity, and adaptive reuse.',
        ],
        [
            'slug' => 'architecture-history',
            'name' => 'Architecture and History Route',
            'duration' => '60 minutes',
            'stops' => 6,
            'distance' => 'Walking distance to be verified',
            'difficulty' => 'Moderate',
            'description' => 'A route for visitors who want to observe structure, material, layout, and heritage character.',
        ],
        [
            'slug' => 'accessible',
            'name' => 'Accessible Route',
            'duration' => '45 minutes',
            'stops' => 5,
            'distance' => 'Step-free sections to be verified',
            'difficulty' => 'Easy',
            'description' => 'A slower-paced route using stops marked as more accessible in the current route data.',
        ],
    ],

    // Draft stop names below can be refined when verified Kota Jail tour-stop names are provided.
    'tour_stops' => [
        [
            'number' => 1,
            'slug' => 'main-entrance',
            'title' => 'Main Entrance',
            'category' => 'Heritage',
            'tags' => ['History', 'Architecture', 'Outdoor', 'Accessible'],
            'image' => $imageMetadata['stops']['main-entrance']['image'],
            'alt' => $imageMetadata['stops']['main-entrance']['alt'],
            'image_credit' => $imageMetadata['stops']['main-entrance']['credit'],
            'image_source_name' => $imageMetadata['stops']['main-entrance']['source_name'],
            'image_source_url' => $imageMetadata['stops']['main-entrance']['source_url'],
            'image_photographer' => $imageMetadata['stops']['main-entrance']['photographer'],
            'image_position' => $imageMetadata['stops']['main-entrance']['position'],
            'image_width' => $imageMetadata['stops']['main-entrance']['width'],
            'image_height' => $imageMetadata['stops']['main-entrance']['height'],
            'excerpt' => 'Begin at the threshold of the former Ayer Molek Prison site and set the tone for a respectful visit.',
            'detail' => 'This opening stop introduces Kota Jail as a Johor Bahru heritage destination shaped by history, architecture, art, and community reuse. The exact interpretive text should be reviewed with the site team before public launch.',
            'original_function' => 'Former entrance or arrival point, to be verified.',
            'current_function' => 'Visitor arrival, orientation, and first tour checkpoint.',
            'features' => ['Entry threshold', 'Wayfinding opportunity', 'Heritage facade character'],
            'context' => 'Use this stop to explain how visitors should move through the site thoughtfully and observe remaining architectural details without sensationalising prison history.',
            'facts' => ['Kota Jail is associated with the former Ayer Molek Prison.', 'The public identity of the site now includes art, heritage, and culture.', 'Specific building functions should be verified before publication.'],
            'did_you_know' => 'A strong first stop helps visitors understand that this is a heritage experience, not a themed attraction.',
            'duration' => '5 min',
            'reading_time' => '3 min read',
            'accessibility' => 'Outdoor orientation point. Surface conditions and step-free access should be verified on site.',
            'coordinates' => ['x' => 18, 'y' => 76],
            'routes' => ['highlights', 'heritage', 'complete', 'accessible'],
            'audio' => [
                'title' => 'Welcome to Kota Jail',
                'duration' => '02:15',
                'src' => null,
                'transcript' => 'Welcome to Kota Jail, a heritage site in Johor Bahru connected to the former Ayer Molek Prison. This sample guide invites visitors to move slowly, read carefully, and treat the place with respect.',
            ],
        ],
        [
            'number' => 2,
            'slug' => 'administration-building',
            'title' => 'Administration Building',
            'category' => 'Architecture',
            'tags' => ['Architecture', 'History', 'Indoor'],
            'image' => $imageMetadata['stops']['administration-building']['image'],
            'alt' => $imageMetadata['stops']['administration-building']['alt'],
            'image_credit' => $imageMetadata['stops']['administration-building']['credit'],
            'image_source_name' => $imageMetadata['stops']['administration-building']['source_name'],
            'image_source_url' => $imageMetadata['stops']['administration-building']['source_url'],
            'image_photographer' => $imageMetadata['stops']['administration-building']['photographer'],
            'image_position' => $imageMetadata['stops']['administration-building']['position'],
            'image_width' => $imageMetadata['stops']['administration-building']['width'],
            'image_height' => $imageMetadata['stops']['administration-building']['height'],
            'excerpt' => 'Pause at a building area that can help explain how the former institution was organised.',
            'detail' => 'The administration building name is a working label. The stop is designed for interpretation about institutional layout, material character, and the process of adapting older buildings for public cultural use.',
            'original_function' => 'Administrative use, to be verified.',
            'current_function' => 'Interpretive and visitor support area, to be verified.',
            'features' => ['Concrete surfaces', 'Older openings', 'Potential archival display zone'],
            'context' => 'Focus on how built form communicates order, movement, and authority, while keeping the wording factual and measured.',
            'facts' => ['Kota Jail is presented publicly as a playground for art, heritage, and culture.', 'The site is in Johor Bahru.', 'Detailed room names require official confirmation.'],
            'did_you_know' => 'Adaptive reuse often keeps traces of old layouts while introducing safer, more welcoming public circulation.',
            'duration' => '6 min',
            'reading_time' => '4 min read',
            'accessibility' => 'Indoor access and ramps should be verified. Provide a bypass route where needed.',
            'coordinates' => ['x' => 28, 'y' => 62],
            'routes' => ['heritage', 'complete', 'architecture-history'],
            'audio' => [
                'title' => 'Reading an Institutional Building',
                'duration' => '03:10',
                'src' => null,
                'transcript' => 'At this stop, visitors can observe the arrangement of entrances, walls, windows, and circulation. These details can help explain how older buildings are adapted for new public purposes.',
            ],
        ],
        [
            'number' => 3,
            'slug' => 'former-prison-corridor',
            'title' => 'Former Prison Corridor',
            'category' => 'History',
            'tags' => ['History', 'Architecture', 'Indoor'],
            'image' => $imageMetadata['stops']['former-prison-corridor']['image'],
            'alt' => $imageMetadata['stops']['former-prison-corridor']['alt'],
            'image_credit' => $imageMetadata['stops']['former-prison-corridor']['credit'],
            'image_source_name' => $imageMetadata['stops']['former-prison-corridor']['source_name'],
            'image_source_url' => $imageMetadata['stops']['former-prison-corridor']['source_url'],
            'image_photographer' => $imageMetadata['stops']['former-prison-corridor']['photographer'],
            'image_position' => $imageMetadata['stops']['former-prison-corridor']['position'],
            'image_width' => $imageMetadata['stops']['former-prison-corridor']['width'],
            'image_height' => $imageMetadata['stops']['former-prison-corridor']['height'],
            'excerpt' => 'Walk through a corridor-style space and reflect on movement, memory, and reuse.',
            'detail' => 'This draft stop should be revised with verified corridor history. The designed interpretation avoids dramatic language and instead encourages close observation of material, light, ventilation, and circulation.',
            'original_function' => 'Former circulation corridor, to be verified.',
            'current_function' => 'Self-guided interpretive passage, to be verified.',
            'features' => ['Linear circulation', 'Repeated openings', 'Filtered natural light'],
            'context' => 'Corridors can be powerful heritage spaces because they connect architecture to lived movement. Keep visitor guidance calm, clear, and respectful.',
            'facts' => ['The site has a former prison identity.', 'Visitors should avoid entering restricted areas.', 'Detailed historic use must be verified.'],
            'did_you_know' => 'Small architectural details such as vents, thresholds, and repaired surfaces often help visitors understand a building better than labels alone.',
            'duration' => '7 min',
            'reading_time' => '4 min read',
            'accessibility' => 'Check corridor width, floor changes, lighting levels, and seating availability before final publication.',
            'coordinates' => ['x' => 43, 'y' => 60],
            'routes' => ['highlights', 'heritage', 'complete', 'architecture-history'],
            'audio' => [
                'title' => 'Movement Through the Site',
                'duration' => '03:45',
                'src' => null,
                'transcript' => 'As you move through this corridor, notice how light, sound, and scale change. This guide uses observation as a way to understand the former site without turning difficult history into spectacle.',
            ],
        ],
        [
            'number' => 4,
            'slug' => 'former-cell',
            'title' => 'Former Cell',
            'category' => 'History',
            'tags' => ['History', 'Indoor'],
            'image' => $imageMetadata['stops']['former-cell']['image'],
            'alt' => $imageMetadata['stops']['former-cell']['alt'],
            'image_credit' => $imageMetadata['stops']['former-cell']['credit'],
            'image_source_name' => $imageMetadata['stops']['former-cell']['source_name'],
            'image_source_url' => $imageMetadata['stops']['former-cell']['source_url'],
            'image_photographer' => $imageMetadata['stops']['former-cell']['photographer'],
            'image_position' => $imageMetadata['stops']['former-cell']['position'],
            'image_width' => $imageMetadata['stops']['former-cell']['width'],
            'image_height' => $imageMetadata['stops']['former-cell']['height'],
            'excerpt' => 'A quiet stop for careful interpretation of confinement, space, and memory.',
            'detail' => 'This stop requires verified interpretation before public use. The draft copy is intentionally restrained and reminds visitors that prison history involves real people and should not be treated as entertainment.',
            'original_function' => 'Former cell, to be verified.',
            'current_function' => 'Interpretive heritage point, to be verified.',
            'features' => ['Small room scale', 'Durable surfaces', 'Controlled openings'],
            'context' => 'Use direct, sensitive language here. Avoid theatrical effects, exaggerated claims, or invented personal stories.',
            'facts' => ['This sample stop name must be verified.', 'Visitors should follow posted safety guidance.', 'Any detailed narratives should come from approved archival sources.'],
            'did_you_know' => 'Respectful interpretation can acknowledge difficult histories while giving visitors space to think.',
            'duration' => '8 min',
            'reading_time' => '5 min read',
            'accessibility' => 'May involve narrower interiors or uneven surfaces. Confirm before marking as accessible.',
            'coordinates' => ['x' => 55, 'y' => 57],
            'routes' => ['heritage', 'complete'],
            'audio' => [
                'title' => 'A Respectful Pause',
                'duration' => '04:00',
                'src' => null,
                'transcript' => 'This is a place for quiet interpretation. The purpose of the guide is to support understanding, not to dramatise confinement or suffering.',
            ],
        ],
        [
            'number' => 5,
            'slug' => 'central-courtyard',
            'title' => 'Central Courtyard',
            'category' => 'Outdoor',
            'tags' => ['Outdoor', 'Heritage', 'Accessible', 'Culture'],
            'image' => $imageMetadata['stops']['central-courtyard']['image'],
            'alt' => $imageMetadata['stops']['central-courtyard']['alt'],
            'image_credit' => $imageMetadata['stops']['central-courtyard']['credit'],
            'image_source_name' => $imageMetadata['stops']['central-courtyard']['source_name'],
            'image_source_url' => $imageMetadata['stops']['central-courtyard']['source_url'],
            'image_photographer' => $imageMetadata['stops']['central-courtyard']['photographer'],
            'image_position' => $imageMetadata['stops']['central-courtyard']['position'],
            'image_width' => $imageMetadata['stops']['central-courtyard']['width'],
            'image_height' => $imageMetadata['stops']['central-courtyard']['height'],
            'excerpt' => 'Step into a shared open area that can host orientation, rest, and reflection.',
            'detail' => 'The courtyard stop frames the site as a place of public gathering and adaptive reuse. Verify the exact name, access routes, shade, and seating before final publication.',
            'original_function' => 'Open yard or circulation space, to be verified.',
            'current_function' => 'Gathering, resting, and programme space, to be verified.',
            'features' => ['Open-air volume', 'Sightlines across the site', 'Potential event setting'],
            'context' => 'This stop can bridge the site past with its present-day community use.',
            'facts' => ['Kota Jail is now associated with visitor experiences and community activities.', 'Outdoor comfort can vary by weather.', 'Programme use should be checked against current operations.'],
            'did_you_know' => 'Open spaces are often where visitors best understand the scale and orientation of a heritage site.',
            'duration' => '6 min',
            'reading_time' => '3 min read',
            'accessibility' => 'Potentially suitable as a rest point. Confirm shade, seating, and surface conditions.',
            'coordinates' => ['x' => 52, 'y' => 42],
            'routes' => ['highlights', 'heritage', 'complete', 'accessible', 'art-culture'],
            'audio' => [
                'title' => 'A Shared Open Space',
                'duration' => '02:50',
                'src' => null,
                'transcript' => 'The courtyard gives visitors a place to pause and read the site as a whole. Look for how buildings, pathways, and current programming meet in this shared area.',
            ],
        ],
        [
            'number' => 6,
            'slug' => 'historical-exhibition',
            'title' => 'Historical Exhibition',
            'category' => 'Heritage',
            'tags' => ['Heritage', 'History', 'Indoor', 'Accessible'],
            'image' => $imageMetadata['stops']['historical-exhibition']['image'],
            'alt' => $imageMetadata['stops']['historical-exhibition']['alt'],
            'image_credit' => $imageMetadata['stops']['historical-exhibition']['credit'],
            'image_source_name' => $imageMetadata['stops']['historical-exhibition']['source_name'],
            'image_source_url' => $imageMetadata['stops']['historical-exhibition']['source_url'],
            'image_photographer' => $imageMetadata['stops']['historical-exhibition']['photographer'],
            'image_position' => $imageMetadata['stops']['historical-exhibition']['position'],
            'image_width' => $imageMetadata['stops']['historical-exhibition']['width'],
            'image_height' => $imageMetadata['stops']['historical-exhibition']['height'],
            'excerpt' => 'Read curated material that can introduce the site timeline and conservation approach.',
            'detail' => 'This stop is designed for a future or current exhibition area. Replace the sample text with approved curatorial content, object captions, and source notes.',
            'original_function' => 'Former room use to be verified.',
            'current_function' => 'Historical exhibition or interpretive area, to be verified.',
            'features' => ['Document-style displays', 'Photographic interpretation', 'Visitor reading zone'],
            'context' => 'Use this page structure for approved timelines, photographs, and short explanations.',
            'facts' => ['The public site references 1883.', 'Official opening hours are listed as daily, 10am to 10pm.', 'Exhibition details should be updated as programmes change.'],
            'did_you_know' => 'Short, sourced captions are often more useful on a walking tour than long walls of text.',
            'duration' => '10 min',
            'reading_time' => '5 min read',
            'accessibility' => 'Provide seated reading options, clear captions, and sufficient lighting where possible.',
            'coordinates' => ['x' => 68, 'y' => 47],
            'routes' => ['highlights', 'heritage', 'complete', 'accessible'],
            'audio' => [
                'title' => 'Exhibiting a Working History',
                'duration' => '04:20',
                'src' => null,
                'transcript' => 'Exhibition spaces can connect historical material with present-day questions about conservation, memory, and civic life.',
            ],
        ],
        [
            'number' => 7,
            'slug' => 'art-gallery',
            'title' => 'Art Gallery',
            'category' => 'Art',
            'tags' => ['Art', 'Indoor', 'Culture', 'Accessible'],
            'image' => $imageMetadata['stops']['art-gallery']['image'],
            'alt' => $imageMetadata['stops']['art-gallery']['alt'],
            'image_credit' => $imageMetadata['stops']['art-gallery']['credit'],
            'image_source_name' => $imageMetadata['stops']['art-gallery']['source_name'],
            'image_source_url' => $imageMetadata['stops']['art-gallery']['source_url'],
            'image_photographer' => $imageMetadata['stops']['art-gallery']['photographer'],
            'image_position' => $imageMetadata['stops']['art-gallery']['position'],
            'image_width' => $imageMetadata['stops']['art-gallery']['width'],
            'image_height' => $imageMetadata['stops']['art-gallery']['height'],
            'excerpt' => 'Explore how contemporary art can give new public life to a former institutional site.',
            'detail' => 'Kota Jail is publicly associated with art, heritage, and culture. This sample stop should be updated with current exhibition titles, artist names, and curatorial notes when available.',
            'original_function' => 'Former room use to be verified.',
            'current_function' => 'Art gallery or exhibition space, to be verified.',
            'features' => ['White wall displays', 'Industrial roof details', 'Contemporary intervention'],
            'context' => 'This stop should celebrate creative reuse while keeping the older site identity visible and respectfully interpreted.',
            'facts' => ['Art is a current public theme of Kota Jail.', 'Exhibition schedules may change.', 'Artist and artwork details must be confirmed.'],
            'did_you_know' => 'Adaptive reuse can make heritage buildings active again by bringing new cultural audiences into them.',
            'duration' => '9 min',
            'reading_time' => '4 min read',
            'accessibility' => 'Gallery circulation, seating, captions, and lighting should be checked before launch.',
            'coordinates' => ['x' => 75, 'y' => 37],
            'routes' => ['art-culture', 'complete', 'accessible'],
            'audio' => [
                'title' => 'Art in a Heritage Setting',
                'duration' => '03:35',
                'src' => null,
                'transcript' => 'In an adaptive reuse project, contemporary art can sit beside older material traces. The contrast can help visitors notice both past and present more clearly.',
            ],
        ],
        [
            'number' => 8,
            'slug' => 'cultural-space',
            'title' => 'Cultural Space',
            'category' => 'Culture',
            'tags' => ['Culture', 'Community', 'Indoor', 'Outdoor'],
            'image' => $imageMetadata['stops']['cultural-space']['image'],
            'alt' => $imageMetadata['stops']['cultural-space']['alt'],
            'image_credit' => $imageMetadata['stops']['cultural-space']['credit'],
            'image_source_name' => $imageMetadata['stops']['cultural-space']['source_name'],
            'image_source_url' => $imageMetadata['stops']['cultural-space']['source_url'],
            'image_photographer' => $imageMetadata['stops']['cultural-space']['photographer'],
            'image_position' => $imageMetadata['stops']['cultural-space']['position'],
            'image_width' => $imageMetadata['stops']['cultural-space']['width'],
            'image_height' => $imageMetadata['stops']['cultural-space']['height'],
            'excerpt' => 'A flexible stop for talks, workshops, creative gatherings, and community-led programming.',
            'detail' => 'This draft section is for a space connected with cultural activity. Confirm the venue name, regular uses, and operating rules with Kota Jail before publishing.',
            'original_function' => 'Former room or yard use to be verified.',
            'current_function' => 'Cultural programme space, to be verified.',
            'features' => ['Flexible layout', 'Event-ready area', 'Community programming potential'],
            'context' => 'Use this stop to show that heritage sites can support contemporary public life without erasing their histories.',
            'facts' => ['Culture is a current public theme of Kota Jail.', 'Events should be confirmed before listing.', 'Some areas may be restricted during setup.'],
            'did_you_know' => 'The most successful heritage programmes often combine interpretation with everyday public use.',
            'duration' => '7 min',
            'reading_time' => '3 min read',
            'accessibility' => 'Event layouts may change access routes. Check each programme setup.',
            'coordinates' => ['x' => 63, 'y' => 25],
            'routes' => ['art-culture', 'complete'],
            'audio' => [
                'title' => 'Culture and Community',
                'duration' => '03:00',
                'src' => null,
                'transcript' => 'This stop looks at how cultural use can bring people together around a historic place while keeping interpretation thoughtful and grounded.',
            ],
        ],
        [
            'number' => 9,
            'slug' => 'heritage-architecture-zone',
            'title' => 'Heritage Architecture Zone',
            'category' => 'Architecture',
            'tags' => ['Architecture', 'Heritage', 'Outdoor'],
            'image' => $imageMetadata['stops']['heritage-architecture-zone']['image'],
            'alt' => $imageMetadata['stops']['heritage-architecture-zone']['alt'],
            'image_credit' => $imageMetadata['stops']['heritage-architecture-zone']['credit'],
            'image_source_name' => $imageMetadata['stops']['heritage-architecture-zone']['source_name'],
            'image_source_url' => $imageMetadata['stops']['heritage-architecture-zone']['source_url'],
            'image_photographer' => $imageMetadata['stops']['heritage-architecture-zone']['photographer'],
            'image_position' => $imageMetadata['stops']['heritage-architecture-zone']['position'],
            'image_width' => $imageMetadata['stops']['heritage-architecture-zone']['width'],
            'image_height' => $imageMetadata['stops']['heritage-architecture-zone']['height'],
            'excerpt' => 'Study materials, thresholds, openings, and repairs as part of the site story.',
            'detail' => 'This stop gathers architectural observation in one place. The exact area name is a draft label and should be replaced with verified site terminology.',
            'original_function' => 'Architectural zone to be verified.',
            'current_function' => 'Observation and interpretation area.',
            'features' => ['Brick and concrete textures', 'Metal details', 'Ventilation and shade patterns'],
            'context' => 'Encourage visitors to look closely, stay behind barriers, and avoid touching fragile material.',
            'facts' => ['Architectural character is part of the visitor experience.', 'Conservation information should be verified.', 'Some details may be protected or restricted.'],
            'did_you_know' => 'Repairs and later changes can be as informative as original fabric when they are interpreted carefully.',
            'duration' => '8 min',
            'reading_time' => '4 min read',
            'accessibility' => 'Outdoor route. Verify slope, surface, and shade for comfort.',
            'coordinates' => ['x' => 35, 'y' => 31],
            'routes' => ['architecture-history', 'complete'],
            'audio' => [
                'title' => 'Reading Materials',
                'duration' => '03:40',
                'src' => null,
                'transcript' => 'Look at the materials around you: concrete, brick, timber, metal, and repaired surfaces. Each one can reveal something about construction, maintenance, and reuse.',
            ],
        ],
        [
            'number' => 10,
            'slug' => 'final-reflection-area',
            'title' => 'Final Reflection Area',
            'category' => 'Reflection',
            'tags' => ['Heritage', 'Outdoor', 'Accessible'],
            'image' => $imageMetadata['stops']['final-reflection-area']['image'],
            'alt' => $imageMetadata['stops']['final-reflection-area']['alt'],
            'image_credit' => $imageMetadata['stops']['final-reflection-area']['credit'],
            'image_source_name' => $imageMetadata['stops']['final-reflection-area']['source_name'],
            'image_source_url' => $imageMetadata['stops']['final-reflection-area']['source_url'],
            'image_photographer' => $imageMetadata['stops']['final-reflection-area']['photographer'],
            'image_position' => $imageMetadata['stops']['final-reflection-area']['position'],
            'image_width' => $imageMetadata['stops']['final-reflection-area']['width'],
            'image_height' => $imageMetadata['stops']['final-reflection-area']['height'],
            'excerpt' => 'Complete the tour with a calm summary of heritage, memory, creativity, and civic reuse.',
            'detail' => 'The final stop gives visitors a place to consider what they have seen and how historic sites can be cared for. Replace this copy with a verified closing message if Kota Jail provides one.',
            'original_function' => 'Site function to be verified.',
            'current_function' => 'Reflection and tour completion point.',
            'features' => ['Quiet pause point', 'Exit wayfinding', 'Visitor feedback opportunity'],
            'context' => 'The closing note should be thoughtful and brief, encouraging visitors to support respectful heritage tourism.',
            'facts' => ['Kota Jail is located in Johor Bahru.', 'The site is open to public visitor experiences.', 'Final visitor guidance should match current operating rules.'],
            'did_you_know' => 'A self-guided tour can be updated quickly as new research, exhibitions, and visitor facilities are confirmed.',
            'duration' => '5 min',
            'reading_time' => '3 min read',
            'accessibility' => 'Potential accessible finish point. Verify seating, shade, and exit route.',
            'coordinates' => ['x' => 22, 'y' => 21],
            'routes' => ['highlights', 'heritage', 'complete', 'accessible'],
            'audio' => [
                'title' => 'Completing the Visit',
                'duration' => '02:30',
                'src' => null,
                'transcript' => 'Thank you for taking a thoughtful walk through Kota Jail. The site brings together history, architecture, art, culture, and community use in the heart of Johor Bahru.',
            ],
        ],
    ],

    // Sample event content. Replace with current official Kota Jail programming before public use.
    'events' => [
        [
            'slug' => 'heritage-night-walk',
            'title' => 'Heritage Night Walk',
            'category' => 'Heritage',
            'status' => 'Upcoming',
            'date' => '2026-08-08',
            'start_time' => '20:00',
            'end_time' => '21:30',
            'venue' => 'Kota Jail Courtyard',
            'image' => $imageMetadata['events']['heritage-night-walk']['image'],
            'alt' => $imageMetadata['events']['heritage-night-walk']['alt'],
            'image_credit' => $imageMetadata['events']['heritage-night-walk']['credit'],
            'image_source_name' => $imageMetadata['events']['heritage-night-walk']['source_name'],
            'image_source_url' => $imageMetadata['events']['heritage-night-walk']['source_url'],
            'image_photographer' => $imageMetadata['events']['heritage-night-walk']['photographer'],
            'image_position' => $imageMetadata['events']['heritage-night-walk']['position'],
            'image_width' => $imageMetadata['events']['heritage-night-walk']['width'],
            'image_height' => $imageMetadata['events']['heritage-night-walk']['height'],
            'excerpt' => 'A sample evening programme focused on architecture, memory, and careful site observation.',
            'description' => 'This sample listing demonstrates how heritage programmes can be presented. Confirm programme title, route, capacity, and guide details before use.',
            'programme' => ['Visitor briefing', 'Slow walk through selected heritage stops', 'Reflection and questions'],
            'registration' => 'Registration details to be verified.',
            'ticket' => 'Ticket information to be verified.',
            'organiser' => 'Kota Jail programme team, to be verified.',
        ],
        [
            'slug' => 'creative-reuse-exhibition',
            'title' => 'Creative Reuse Exhibition',
            'category' => 'Exhibition',
            'status' => 'Current',
            'date' => '2026-07-19',
            'start_time' => '10:00',
            'end_time' => '22:00',
            'venue' => 'Historical Exhibition Area',
            'image' => $imageMetadata['events']['creative-reuse-exhibition']['image'],
            'alt' => $imageMetadata['events']['creative-reuse-exhibition']['alt'],
            'image_credit' => $imageMetadata['events']['creative-reuse-exhibition']['credit'],
            'image_source_name' => $imageMetadata['events']['creative-reuse-exhibition']['source_name'],
            'image_source_url' => $imageMetadata['events']['creative-reuse-exhibition']['source_url'],
            'image_photographer' => $imageMetadata['events']['creative-reuse-exhibition']['photographer'],
            'image_position' => $imageMetadata['events']['creative-reuse-exhibition']['position'],
            'image_width' => $imageMetadata['events']['creative-reuse-exhibition']['width'],
            'image_height' => $imageMetadata['events']['creative-reuse-exhibition']['height'],
            'excerpt' => 'A sample exhibition page about turning former institutional spaces into cultural destinations.',
            'description' => 'Use this entry as editable exhibition content with verified curator notes, artist credits, and visitor guidance.',
            'programme' => ['Open gallery hours', 'Short interpretive captions', 'Self-guided visitor route'],
            'registration' => 'Walk-in information to be verified.',
            'ticket' => 'Admission information to be verified.',
            'organiser' => 'Kota Jail and partners, to be verified.',
        ],
        [
            'slug' => 'architecture-sketch-session',
            'title' => 'Architecture Sketch Session',
            'category' => 'Workshop',
            'status' => 'Upcoming',
            'date' => '2026-08-22',
            'start_time' => '09:30',
            'end_time' => '12:00',
            'venue' => 'Heritage Architecture Zone',
            'image' => $imageMetadata['events']['architecture-sketch-session']['image'],
            'alt' => $imageMetadata['events']['architecture-sketch-session']['alt'],
            'image_credit' => $imageMetadata['events']['architecture-sketch-session']['credit'],
            'image_source_name' => $imageMetadata['events']['architecture-sketch-session']['source_name'],
            'image_source_url' => $imageMetadata['events']['architecture-sketch-session']['source_url'],
            'image_photographer' => $imageMetadata['events']['architecture-sketch-session']['photographer'],
            'image_position' => $imageMetadata['events']['architecture-sketch-session']['position'],
            'image_width' => $imageMetadata['events']['architecture-sketch-session']['width'],
            'image_height' => $imageMetadata['events']['architecture-sketch-session']['height'],
            'excerpt' => 'A sample workshop for observing heritage materials, lines, and light through drawing.',
            'description' => 'This workshop listing is sample content. Replace with confirmed facilitator, materials, capacity, and weather plan.',
            'programme' => ['Orientation', 'Sketching exercise', 'Group sharing'],
            'registration' => 'Online registration details to be confirmed.',
            'ticket' => 'Fee details to be verified.',
            'organiser' => 'Workshop organiser to be verified.',
        ],
        [
            'slug' => 'community-culture-market',
            'title' => 'Community Culture Market',
            'category' => 'Community',
            'status' => 'Upcoming',
            'date' => '2026-09-05',
            'start_time' => '16:00',
            'end_time' => '21:00',
            'venue' => 'Cultural Space',
            'image' => $imageMetadata['events']['community-culture-market']['image'],
            'alt' => $imageMetadata['events']['community-culture-market']['alt'],
            'image_credit' => $imageMetadata['events']['community-culture-market']['credit'],
            'image_source_name' => $imageMetadata['events']['community-culture-market']['source_name'],
            'image_source_url' => $imageMetadata['events']['community-culture-market']['source_url'],
            'image_photographer' => $imageMetadata['events']['community-culture-market']['photographer'],
            'image_position' => $imageMetadata['events']['community-culture-market']['position'],
            'image_width' => $imageMetadata['events']['community-culture-market']['width'],
            'image_height' => $imageMetadata['events']['community-culture-market']['height'],
            'excerpt' => 'A sample community event format for local makers, food, and small performances.',
            'description' => 'Use this as an editable example for community programming. Vendor, accessibility, and traffic information should be verified.',
            'programme' => ['Local makers', 'Food and beverage pop-ups', 'Community performance slot'],
            'registration' => 'Vendor and visitor information to be verified.',
            'ticket' => 'Admission information to be verified.',
            'organiser' => 'Community partner to be verified.',
        ],
        [
            'slug' => 'past-art-open-studio',
            'title' => 'Past Art Open Studio',
            'category' => 'Art',
            'status' => 'Past',
            'date' => '2026-06-15',
            'start_time' => '14:00',
            'end_time' => '18:00',
            'venue' => 'Art Gallery',
            'image' => $imageMetadata['events']['past-art-open-studio']['image'],
            'alt' => $imageMetadata['events']['past-art-open-studio']['alt'],
            'image_credit' => $imageMetadata['events']['past-art-open-studio']['credit'],
            'image_source_name' => $imageMetadata['events']['past-art-open-studio']['source_name'],
            'image_source_url' => $imageMetadata['events']['past-art-open-studio']['source_url'],
            'image_photographer' => $imageMetadata['events']['past-art-open-studio']['photographer'],
            'image_position' => $imageMetadata['events']['past-art-open-studio']['position'],
            'image_width' => $imageMetadata['events']['past-art-open-studio']['width'],
            'image_height' => $imageMetadata['events']['past-art-open-studio']['height'],
            'excerpt' => 'An example past event card to show archive behaviour and filtering.',
            'description' => 'This entry represents past programme content and can be updated with real summaries and programme notes.',
            'programme' => ['Open studio visit', 'Artist conversation', 'Informal walkthrough'],
            'registration' => 'Closed.',
            'ticket' => 'Past event.',
            'organiser' => 'Organiser to be verified.',
        ],
    ],

    'timeline' => [
        [
            'year' => '1883',
            'title' => 'Ayer Molek Prison Established',
            'description' => 'The public Kota Jail identity references 1883 and its connection to the former Ayer Molek Prison in Johor Bahru.',
        ],
        [
            'year' => 'Former prison period',
            'title' => 'Institutional Use',
            'description' => 'Detailed operational history should be added only from verified sources and approved interpretation.',
        ],
        [
            'year' => 'Heritage conservation',
            'title' => 'Protecting the Site Character',
            'description' => 'Conservation and repair work can help retain important architectural traces while preparing spaces for visitors.',
        ],
        [
            'year' => 'Adaptive reuse',
            'title' => 'A Creative Destination',
            'description' => 'Kota Jail is now presented as a place for art, heritage, culture, and community activities.',
        ],
        [
            'year' => 'Today',
            'title' => 'Self-Guided Visitor Experience',
            'description' => 'The digital tour supports walking, reading, listening, and reflecting across the site at a comfortable pace.',
        ],
    ],

    'visitor_info' => [
        'opening_hours' => 'Open daily, 10:00 AM - 10:00 PM',
        'address' => 'Penjara (lama) Ayer Molek, Jalan Ayer Molek, 80888 Johor Bahru, Malaysia',
        'google_maps_embed_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.517932979787!2d103.7561015!3d1.4628818!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da13006a5afc1b%3A0x129a88a631961dc3!2sKOTAJAIL!5e0!3m2!1sen!2smy!4v1784473933211!5m2!1sen!2smy',
        'google_maps_contact_embed_url' => 'https://www.google.com/maps?q=Kota%20Jail%2C%20Penjara%20Lama%20Ayer%20Molek%2C%20Jalan%20Ayer%20Molek%2C%2080888%20Johor%20Bahru%2C%20Johor%2C%20Malaysia&output=embed',
        'google_maps_search_url' => 'https://www.google.com/maps/search/?api=1&query=Kota+Jail+Penjara+Lama+Ayer+Molek+Johor+Bahru',
        'parking' => 'Parking information requires official verification.',
        'public_transport' => 'Nearest public transport options should be verified before launch.',
        'admission' => 'Admission details require official verification.',
        'accessibility' => 'Accessible routes, ramps, lifts, and rest points should be confirmed on site.',
        'toilets' => 'Toilet locations require official verification.',
        'prayer_room' => 'Prayer room availability requires official verification.',
        'food' => 'Food and beverage availability may change by programme.',
        'rest_areas' => 'Use marked rest areas and follow on-site signs.',
        'photography' => 'Photography rules require official verification. Avoid photographing restricted areas.',
        'safety' => 'Stay within public areas, follow barriers and staff instructions, and use care on uneven surfaces.',
        'weather' => 'Bring water, sun protection, and rain cover when using outdoor routes.',
        'groups' => 'Group visit arrangements require official verification.',
        'emergency' => 'Emergency contact to be confirmed by Kota Jail operations.',
    ],

    'faqs' => [
        [
            'question' => 'Is this self-guided tour official?',
            'answer' => 'This Laravel website is built as a display-ready digital tour structure. Historical details, stop names, and visitor facilities should be verified with Kota Jail before publication.',
        ],
        [
            'question' => 'Do I need to log in to save progress?',
            'answer' => 'No. Progress is saved only in this browser using local storage. It is private to the device and can be reset at any time.',
        ],
        [
            'question' => 'Can I use the tour without audio?',
            'answer' => 'Yes. Every stop includes readable content and an audio transcript area. Audio files can be added later without changing the page structure.',
        ],
        [
            'question' => 'Are all areas accessible?',
            'answer' => 'Some accessibility information should be checked on site. The website includes list views, large tap targets, and route preferences to support planning.',
        ],
        [
            'question' => 'Can I take photographs?',
            'answer' => 'Photography rules should follow current Kota Jail guidance. Avoid restricted areas, private activities, and any signage that limits photography.',
        ],
    ],

    'gallery' => array_values($imageMetadata['gallery']),

    'planner_profiles' => [
        [
            'name' => 'Best for first-time visitors',
            'route' => '60-Minute Heritage Tour',
            'description' => 'Start with orientation, move through the main heritage stops, then finish with the exhibition and reflection areas.',
            'stops' => ['Main Entrance', 'Former Prison Corridor', 'Central Courtyard', 'Historical Exhibition', 'Final Reflection Area'],
        ],
        [
            'name' => 'Best for families',
            'route' => '30-Minute Highlights Tour',
            'description' => 'A shorter route with frequent pauses, outdoor sections, and simple interpretation.',
            'stops' => ['Main Entrance', 'Central Courtyard', 'Historical Exhibition', 'Final Reflection Area'],
        ],
        [
            'name' => 'Best for architecture enthusiasts',
            'route' => 'Architecture and History Route',
            'description' => 'Focus on building materials, thresholds, ventilation, circulation, and visible signs of reuse.',
            'stops' => ['Administration Building', 'Former Prison Corridor', 'Heritage Architecture Zone', 'Central Courtyard'],
        ],
        [
            'name' => 'Best for art enthusiasts',
            'route' => 'Art and Culture Route',
            'description' => 'Prioritise current creative programming and spaces where art, culture, and heritage meet.',
            'stops' => ['Historical Exhibition', 'Art Gallery', 'Cultural Space', 'Central Courtyard'],
        ],
        [
            'name' => 'Best short route',
            'route' => '30-Minute Highlights Tour',
            'description' => 'A compact introduction for visitors with limited time.',
            'stops' => ['Main Entrance', 'Former Prison Corridor', 'Central Courtyard', 'Final Reflection Area'],
        ],
        [
            'name' => 'Best accessible route',
            'route' => 'Accessible Route',
            'description' => 'A slower route using stops marked as accessible in the route data, subject to on-site verification.',
            'stops' => ['Main Entrance', 'Central Courtyard', 'Historical Exhibition', 'Art Gallery', 'Final Reflection Area'],
        ],
    ],
];
