<?php

$credit = 'Image by Self-Guide Kota Jail Team';
$sourceName = 'Self-Guide Kota Jail Team';

$photos = [
    'corridor' => [
        'image' => 'img_update/gambar1.jpg',
        'alt' => 'Historic corridor inside Kota Jail at Ayer Molek with barred cell doors, aged plaster walls, and a central stair.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 720,
    ],
    'gate' => [
        'image' => 'img_update/gambar2.jpg',
        'alt' => 'Original arched doorway at Kota Jail with black metal grillework and warm light across the old threshold.',
        'position' => 'center 46%',
        'width' => 607,
        'height' => 1080,
    ],
    'justice-display' => [
        'image' => 'img_update/gambar3.jpg',
        'alt' => 'Educational display inside Kota Jail explaining the criminal justice system beside a preserved former cell door.',
        'position' => 'center 46%',
        'width' => 607,
        'height' => 1080,
    ],
    'exhibition-room' => [
        'image' => 'img_update/gambar4.jpg',
        'alt' => 'Preserved exhibition room at Kota Jail with weathered walls, historical objects, and interpretive displays.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 607,
    ],
    'qr-wall' => [
        'image' => 'img_update/gambar5.jpg',
        'alt' => 'Weathered exterior wall at Kota Jail with visitor QR signage and plants along the Ayer Molek walking route.',
        'position' => 'center 48%',
        'width' => 810,
        'height' => 1080,
    ],
    'original-heritage-exterior' => [
        'image' => 'images/kota-jail/hero/kota-jail-heritage-exterior.jpg',
        'alt' => 'Wide exterior view of Kota Jail showing the historic building massing and visitor approach at Ayer Molek.',
        'position' => 'center 48%',
        'width' => 1800,
        'height' => 1080,
    ],
    'original-interior-hall' => [
        'image' => 'images/kota-jail/hero/kota-jail-main-interior-hall.jpg',
        'alt' => 'Large interior hall at Kota Jail with heritage walls, open circulation, and preserved architectural character.',
        'position' => 'center 50%',
        'width' => 1600,
        'height' => 1066,
    ],
    'original-complex-overview' => [
        'image' => 'images/kota-jail/backgrounds/kota-jail-complex-overview.jpg',
        'alt' => 'Elevated overview of the Kota Jail complex showing the arrangement of buildings and visitor movement areas.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 608,
    ],
    'original-visitor-facade' => [
        'image' => 'images/kota-jail/visitor/kota-jail-visitor-facade.jpg',
        'alt' => 'Visitor-facing heritage facade at Kota Jail with preserved exterior character and public approach area.',
        'position' => 'center 48%',
        'width' => 1200,
        'height' => 800,
    ],
    'original-main-entrance' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-main-entrance.jpg',
        'alt' => 'Main entrance area at Kota Jail where visitors orient themselves before entering the heritage route.',
        'position' => 'center 45%',
        'width' => 968,
        'height' => 1000,
    ],
    'original-administration' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-administration-building.jpg',
        'alt' => 'Former administrative building area at Kota Jail showing institutional architecture and public circulation.',
        'position' => 'center 48%',
        'width' => 1000,
        'height' => 600,
    ],
    'original-cell-area' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-cell-area.jpg',
        'alt' => 'Former cell area at Kota Jail with enclosed room scale and preserved interior surfaces.',
        'position' => 'center 50%',
        'width' => 1000,
        'height' => 667,
    ],
    'original-courtyard' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-courtyard.jpg',
        'alt' => 'Courtyard space at Kota Jail used for orientation, gathering, and understanding the site layout.',
        'position' => 'center 50%',
        'width' => 1000,
        'height' => 666,
    ],
    'original-art-gallery' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-art-gallery.jpg',
        'alt' => 'Gallery room at Kota Jail showing adaptive reuse of the former prison setting for art and cultural interpretation.',
        'position' => 'center 50%',
        'width' => 1000,
        'height' => 719,
    ],
    'original-cultural-market' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-cultural-market.jpg',
        'alt' => 'Cultural gathering area at Kota Jail showing contemporary public activity within the heritage site.',
        'position' => 'center 50%',
        'width' => 1000,
        'height' => 719,
    ],
    'original-reflection-space' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-reflection-space.jpg',
        'alt' => 'Quiet reflection space at Kota Jail for completing the self-guided route and considering the site history.',
        'position' => 'center 50%',
        'width' => 1000,
        'height' => 563,
    ],
    'original-architecture-detail' => [
        'image' => 'images/kota-jail/tour-stops/kota-jail-architecture-detail.jpg',
        'alt' => 'Architectural detail at Kota Jail showing aged material surfaces, openings, and conservation traces.',
        'position' => 'center 48%',
        'width' => 1000,
        'height' => 666,
    ],
    'original-gallery-exterior-architecture' => [
        'image' => 'images/kota-jail/gallery/kota-jail-exterior-architecture-01.jpg',
        'alt' => 'Exterior architecture of Kota Jail showing the historic building frontage and preserved institutional form.',
        'position' => 'center 50%',
        'width' => 1200,
        'height' => 720,
    ],
    'original-gallery-abandoned-exterior' => [
        'image' => 'images/kota-jail/gallery/kota-jail-abandoned-exterior-02.jpg',
        'alt' => 'Weathered exterior wall at Kota Jail showing aged surfaces and the passage of time at Ayer Molek.',
        'position' => 'center 48%',
        'width' => 1080,
        'height' => 720,
    ],
    'original-gallery-cell-block' => [
        'image' => 'images/kota-jail/gallery/kota-jail-cell-block-04.jpg',
        'alt' => 'Former cell block view at Kota Jail with repeated openings and preserved interior structure.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 720,
    ],
    'original-gallery-entrance' => [
        'image' => 'images/kota-jail/gallery/kota-jail-entrance-06.jpg',
        'alt' => 'Entrance detail at Kota Jail showing a strong threshold into the former Ayer Molek prison grounds.',
        'position' => 'center 48%',
        'width' => 872,
        'height' => 900,
    ],
    'original-gallery-exhibition' => [
        'image' => 'images/kota-jail/gallery/kota-jail-exhibition-07.jpg',
        'alt' => 'Exhibition display inside Kota Jail connecting preserved rooms with educational interpretation.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 608,
    ],
    'original-gallery-gallery-space' => [
        'image' => 'images/kota-jail/gallery/kota-jail-gallery-space-08.jpg',
        'alt' => 'Gallery space at Kota Jail showing adaptive reuse for art, history, and visitor learning.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 777,
    ],
    'original-gallery-market' => [
        'image' => 'images/kota-jail/gallery/kota-jail-market-09.jpg',
        'alt' => 'Public cultural market area at Kota Jail showing community activity within the heritage grounds.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 777,
    ],
    'original-gallery-overview' => [
        'image' => 'images/kota-jail/gallery/kota-jail-overview-05.jpg',
        'alt' => 'Overview of the Kota Jail site showing the scale and arrangement of the heritage complex.',
        'position' => 'center 50%',
        'width' => 1080,
        'height' => 608,
    ],
];

$image = function (string $key, string $title, ?string $alt = null, ?string $position = null) use ($photos, $credit, $sourceName): array {
    return [
        'title' => $title,
        'image' => $photos[$key]['image'],
        'alt' => $alt ?? $photos[$key]['alt'],
        'credit' => $credit,
        'source_name' => $sourceName,
        'source_url' => null,
        'photographer' => 'Self-Guide Kota Jail Team',
        'position' => $position ?? $photos[$key]['position'],
        'width' => $photos[$key]['width'],
        'height' => $photos[$key]['height'],
    ];
};

return [
    'sections' => [
        'hero' => $image('corridor', 'Kota Jail corridor hero', 'Long historic corridor inside Kota Jail, Ayer Molek, showing barred cell doors, weathered walls, and the building passage visitors encounter on the route.', 'center 52%'),
        'home_credit' => $image('qr-wall', 'Kota Jail QR visitor sign', 'Weathered Kota Jail wall with QR visitor signage used to connect the physical Ayer Molek route with the digital guide.', 'center 48%'),
        'home_intro' => $image('gate', 'Kota Jail barred doorway', 'Arched barred doorway inside Kota Jail, showing the original threshold and metal grillework of the former Ayer Molek prison site.', 'center 45%'),
        'home_features' => $image('original-interior-hall', 'Kota Jail interior route hall', 'Large Kota Jail interior hall showing heritage walls, visitor circulation, and the atmosphere of the self-guided route.', 'center 50%'),
        'home_timeline' => $image('justice-display', 'Kota Jail justice display', 'Educational justice-system display inside Kota Jail, placed beside preserved cell-door details from the old prison setting.', 'center 45%'),
        'home_visit' => $image('original-visitor-facade', 'Kota Jail visitor facade', 'Visitor-facing Kota Jail facade showing the heritage exterior and practical arrival context at Ayer Molek.', 'center 48%'),
        'about_hero' => $image('original-heritage-exterior', 'Kota Jail exterior heritage view', 'Wide exterior view of Kota Jail showing the historic Ayer Molek building frontage and public approach.', 'center 48%'),
        'start_tour_hero' => $image('qr-wall', 'Kota Jail route starting point', 'Exterior QR checkpoint wall at Kota Jail where visitors can begin the Ayer Molek self-guided route.', 'center 48%'),
        'tour_map_hero' => $image('gate', 'Kota Jail tour route gateway', 'Arched barred gateway inside Kota Jail, representing the transition from orientation into the self-guided route.', 'center 45%'),
        'locations_hero' => $image('original-complex-overview', 'Kota Jail route overview', 'Overview of the Kota Jail complex showing how the self-guided route moves through the Ayer Molek site.', 'center 50%'),
        'gallery_hero' => $image('exhibition-room', 'Kota Jail visual archive room', 'Preserved room inside Kota Jail with exhibition displays, weathered walls, and historical objects for visual archive browsing.', 'center 50%'),
        'visitor_hero' => $image('gate', 'Kota Jail visitor information gateway', 'Barred doorway and warm interior light at Kota Jail, used to introduce practical visitor information.', 'center 45%'),
        'plan_visit_hero' => $image('qr-wall', 'Kota Jail planning and QR wall', 'Weathered Kota Jail route wall with QR signage, helping visitors plan their self-guided walk through Ayer Molek.', 'center 48%'),
        'contact_hero' => $image('gate', 'Kota Jail contact gateway', 'Arched metal gate inside Kota Jail, used as a welcoming contact-page image for the Ayer Molek site.', 'center 45%'),
        'about_exterior' => $image('qr-wall', 'Kota Jail weathered exterior wall', 'Original peeling exterior wall at Kota Jail showing age, route signage, and public access along the heritage walkway.', 'center 48%'),
        'about_culture' => $image('exhibition-room', 'Kota Jail exhibition culture room', 'Preserved Kota Jail room adapted for interpretation, with historical objects and marked wall surfaces visible.', 'center 50%'),
        'about_before' => $image('corridor', 'Kota Jail former corridor memory', 'Interior corridor at Kota Jail showing barred cells, older surfaces, and the memory of the former prison layout.', 'center 50%'),
        'about_after' => $image('justice-display', 'Kota Jail current interpretation display', 'Current interpretive display inside Kota Jail beside a preserved cell door, showing education layered into the old building.', 'center 45%'),
        'about_timeline' => $image('original-main-entrance', 'Kota Jail timeline entrance', 'Main entrance area at Kota Jail used to frame the historical timeline and visitor arrival story.', 'center 45%'),
        'about_values' => $image('gate', 'Kota Jail grille and doorway detail', 'Metal grillework and arched doorway inside Kota Jail, highlighting preserved architectural details.', 'center 45%'),
        'error_404' => $image('corridor', 'Kota Jail corridor background', 'Historic Kota Jail corridor background with barred cells and aged interior surfaces.', 'center 52%'),
        'error_500' => $image('gate', 'Kota Jail barred doorway background', 'Kota Jail arched barred doorway background showing preserved grillework and old interior light.', 'center 45%'),
    ],

    'stops' => [
        'main-entrance' => $image('qr-wall', 'Start point QR checkpoint', 'Weathered Kota Jail wall with QR signage marking the start of the self-guided route at Ayer Molek.', 'center 48%'),
        'administration-building' => $image('original-administration', 'Administrative building area', 'Former administrative area at Kota Jail showing institutional architecture and visitor circulation within the Ayer Molek site.', 'center 48%'),
        'former-prison-corridor' => $image('corridor', 'Former prison corridor', 'Long corridor inside Kota Jail with barred cell doors, worn walls, and a central stair showing the old circulation route.', 'center 50%'),
        'former-cell' => $image('original-cell-area', 'Former cell area', 'Former Kota Jail cell area with enclosed room scale, older surfaces, and preserved details for careful interpretation.', 'center 50%'),
        'central-courtyard' => $image('original-courtyard', 'Central courtyard space', 'Courtyard at Kota Jail used for orientation, gathering, rest, and understanding the scale of the former prison grounds.', 'center 50%'),
        'historical-exhibition' => $image('justice-display', 'Historical justice display', 'Interpretive justice-system panel inside Kota Jail beside an old numbered cell door.', 'center 45%'),
        'art-gallery' => $image('exhibition-room', 'Art gallery room', 'Preserved Kota Jail room adapted for displays, visual interpretation, and contemporary cultural use.', 'center 50%'),
        'cultural-space' => $image('original-cultural-market', 'Cultural gathering space', 'Cultural activity area at Kota Jail showing how the former prison grounds can support contemporary community use.', 'center 50%'),
        'heritage-architecture-zone' => $image('gate', 'Architectural gate detail', 'Arched doorway and black metal grille inside Kota Jail, showing original architectural form and controlled access.', 'center 45%'),
        'final-reflection-area' => $image('original-reflection-space', 'Final reflection space', 'Quiet reflection area at Kota Jail where visitors can complete the route and consider the Ayer Molek site history.', 'center 50%'),
    ],

    'gallery' => [
        1 => $image('corridor', 'Corridor Memory', 'Atmospheric Kota Jail corridor with barred cells, a stair, and aged wall surfaces.', 'center 50%') + [
            'id' => 1,
            'category' => 'Historical Photographs',
            'caption' => 'Historic Kota Jail corridor showing barred cell doors, worn plaster, and the controlled movement of the former Ayer Molek prison layout.',
        ],
        2 => $image('gate', 'Barred Gateway', 'Tall arched doorway and metal grille inside Kota Jail.', 'center 45%') + [
            'id' => 2,
            'category' => 'Architecture',
            'caption' => 'Original arched threshold with metal grillework, showing how light, scale, and enclosure shape the visitor experience.',
        ],
        3 => $image('justice-display', 'Justice Display', 'Criminal justice system display beside a former Kota Jail cell door.', 'center 45%') + [
            'id' => 3,
            'category' => 'Exhibitions',
            'caption' => 'Educational display beside a preserved cell door, connecting the former prison site with justice-system interpretation.',
        ],
        4 => $image('qr-wall', 'QR Checkpoint Wall', 'Weathered Kota Jail exterior wall with a QR sign and route-side plants.', 'center 48%') + [
            'id' => 4,
            'category' => 'Visitor Experiences',
            'caption' => 'Visitor QR checkpoint on a weathered Kota Jail wall, linking the physical route to the self-guided digital experience.',
        ],
        5 => $image('original-gallery-exterior-architecture', 'Historic Exterior Form', 'Exterior architecture of Kota Jail with preserved frontage and institutional form.', 'center 50%') + [
            'id' => 5,
            'category' => 'Architecture',
            'caption' => 'The historic exterior form helps visitors read Kota Jail as a former institutional complex adapted for public heritage use.',
        ],
        6 => $image('original-gallery-abandoned-exterior', 'Weathered Exterior Wall', 'Aged exterior wall surface at Kota Jail showing peeling finishes and material wear.', 'center 48%') + [
            'id' => 6,
            'category' => 'Heritage Details',
            'caption' => 'Peeling surfaces and exterior wear reveal the passage of time across the former Ayer Molek prison grounds.',
        ],
        7 => $image('original-gallery-cell-block', 'Cell Door Rhythm', 'Former cell block at Kota Jail with repeated openings and preserved corridor structure.', 'center 50%') + [
            'id' => 7,
            'category' => 'Historical Photographs',
            'caption' => 'Repeated openings and corridor rhythm help visitors understand movement, enclosure, and memory inside the former prison.',
        ],
        8 => $image('original-gallery-entrance', 'Entrance Threshold', 'Entrance detail at Kota Jail marking the transition into the former prison grounds.', 'center 48%') + [
            'id' => 8,
            'category' => 'Architecture',
            'caption' => 'The entrance threshold frames the visitor experience and introduces the controlled architectural language of the site.',
        ],
        9 => $image('original-gallery-exhibition', 'Interpretive Exhibition', 'Exhibition display inside Kota Jail connecting preserved rooms with visitor learning.', 'center 50%') + [
            'id' => 9,
            'category' => 'Exhibitions',
            'caption' => 'Interpretive displays connect the preserved rooms with historical memory, justice-system context, and visitor education.',
        ],
        10 => $image('original-gallery-gallery-space', 'Adaptive Gallery Space', 'Gallery space at Kota Jail adapted for art, history, and visitor reflection.', 'center 50%') + [
            'id' => 10,
            'category' => 'Visual Archives',
            'caption' => 'A gallery room shows how the former prison setting can support contemporary cultural interpretation without erasing its history.',
        ],
        11 => $image('original-gallery-market', 'Community Culture Area', 'Public cultural market area at Kota Jail with people gathering within the heritage grounds.', 'center 50%') + [
            'id' => 11,
            'category' => 'Visitor Experiences',
            'caption' => 'Community activity within the Kota Jail grounds shows how the site can hold present-day public life alongside historical memory.',
        ],
        12 => $image('original-gallery-overview', 'Site Overview', 'Overview of the Kota Jail site showing the scale and arrangement of the heritage complex.', 'center 50%') + [
            'id' => 12,
            'category' => 'Visual Archives',
            'caption' => 'A wider site view helps visitors understand how individual stops connect across the Ayer Molek heritage route.',
        ],
    ],
];
